### ISSUE TITLE
Typo in "if"-statement

### ISSUE THREAD

**Issue by kotwin** [drOpen/DrTest#15]
https://github.com/drOpen/DrTest/blob/4767bcffbd7b162965cb9f23e120ab5f39d0bcfd/DrTestActions/DrTAHelper/DrTestHelper/TAHelper.cs#L86

Excessive closing bracket in "if"-statement. Should be:

`if (IsExpected(result, expected) == false) throw new DrTAExpectedException(result, expected);`

**Comment by drOpen** [comment]
has fixed in the commit 90557a1, thank you very much for your hand
